sudo: required
dist: trusty

language: java
jdk: oraclejdk8

script:
  - ./gradlew clean test


cache:
  directories:
    - $HOME/.gradle
    - $HOME/.jdk

env:
  global:
    - JAVA_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
